Specify schema name explicit in NormalizerTable (#404)
```sql
CREATE INDEX pgroonga_memos_index
          ON memos
       USING pgroonga (content)
        WITH (normalizers='
                NormalizerNFKC130,
                NormalizerTable(
                  "normalized", "${table:pgrn_normalizations_index}.normalized", 
                  "target", "target"
                )
             ');
ERROR:  relation "pgrn_normalizations_index" does not exist
```

Fix: change `"${table:pgrn_normalizations_index}.normalized"` to
`"${table:public.pgrn_normalizations_index}.normalized"`

PostgreSQL implicitly change `search_path` to `pg_catalog` and `pg_temp`
while execute `CREATE INDEX` since PostgreSQL 17.

See: 
* https://www.postgresql.org/docs/current/release-17.html
*
https://github.com/postgres/postgres/commit/05e17373517114167d002494e004fa0aa32d1fd1

So, We need to specify schema name explicit in `NormalizerTable`.
After change `CREATE INDEX` is work even if PostgreSQL 16 or earlier.

---------

Co-authored-by: Horimoto Yasuhiro <horimoto@clear-code.com>